export const CHARACTER_REQUEST = 'CHARACTER_REQUEST';
export const CHARACTER_FAILURE = 'CHARACTER_FAILURE';
export const CHARACTER_SUCCESS = 'CHARACTER_SUCCESS';

export const FILMS_REQUEST = 'FILMS_REQUEST';
export const FILMS_FAILURE = 'FILMS_FAILURE';
export const FILMS_SUCCESS = 'FILMS_SUCCESS';