export const PEOPLE_REQUEST = 'PEOPLE_REQUEST';
export const PEOPLE_SUCCESS = 'PEOPLE_SUCCESS';
export const PEOPLE_SERCHED_SUCCESS = 'PEOPLE_SERCHED_SUCCESS';
export const PEOPLE_FAILURE = 'PEOPLE_FAILURE';

export const PEOPLE_ADD_TO_FAVORITE = 'PEOPLE_ADD_TO_FAVORITE';
export const PEOPLE_REMOVE_FROM_FAVORITE = 'PEOPLE_REMOVE_FROM_FAVORITE';
export const PEOPLE_CHANGE_CURRENT_PAGE = 'PEOPLE_CHANGE_CURRENT_PAGE';

// export const PEOPLE_SORT_PAGE = 'PEOPLE_SORT_PAGE';